### ISSUE TITLE
[Other Wallet] Other wallet's portfolio

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#157]
## Acceptance criteria
- [ ] Please check my portfolio stories
- [ ] I can visit other wallet's portfolios when I click their address 

Where to find the address of others
- [ ] Validator's details
- [ ] Proposal vote results
- [ ] Proposal comments
- [ ] Transaction history
- [ ] Direct link

## State
- Don't have this wallet(e.g. wrong URL) --> Generic error page and msg `Address Not Found` with back to homepage button

## Remarks
Differences between my portfolio
1. Not "Your Stakes" but "Delegation"
2. No "Transaction" history
3. Don't have its own tab on the sidebar

## Design
![image.png](https://zube.io/files/oursky/c6bed79189033b9a7cc3c83f278987db-image.png)

**Comment by ivanng-oursky** [comment]
### Tasks
- UI: Create other's portfolio screen [5]

<details>

### Implementation details

#### API

- Update portfolio screen API to take address input so they can be reused here [1]

#### UI

- Create others portfolio (accounts) screen component [0.5]
- Add links to all addresses appearing other pages [1]
- Reuse all components from oursky/likedao#108, oursky/likedao#109 , oursky/likedao#91, oursky/likedao#112, oursky/likedao#110 [1]
- Integrate components with API [0.5]
- Create generic error page, can reuse page from oursky/likedao#42 [1]

</details>

**Comment by ivanng-oursky** [comment]
@mitchellchou 

Comparing ours vs desmos' implementation of wallet balance, there seems to be some inconsistency. Desmos also take in commissions and rewards when calculating total balance, resulting in a higher total balance than our implementation. 

our implementation:
```
total balance = available balance + staked balance + unstaking balance
```

desmos implementation
```
total balance = available balance + staked balance + unstaking balance + reward + commission
```

<img width="980" alt="image" src="https://user-images.githubusercontent.com/106721852/175200310-9663d0bd-1fdc-4e80-b4f0-807d59b15f2c.png">

<img width="1814" alt="image" src="https://user-images.githubusercontent.com/106721852/175200455-50b352e8-f35f-4649-a738-f23d916db549.png">

[https://testnet.likecoin.bigdipper.live/accounts/like1ewpwcdfgsdfdu0jj2unwhjjl58yshm9xnvr9c2](https://testnet.likecoin.bigdipper.live/accounts/like1ewpwcdfgsdfdu0jj2unwhjjl58yshm9xnvr9c2)

**Comment by mitchellchou** [comment]
@ivanng-oursky Please use this formula and add the 2 new fields
```
total balance = available balance + staked balance + unstaking balance + reward + commission
```

And default show all fields even if the value is 0 (I'll consult designer for this logic and come back to you if any update)

**Comment by ivanng-oursky** [comment]
@mitchellchou 😭 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/106721852/175518904-a49ccfb9-4201-478c-a430-472c2ee8db6c.png">

**Comment by chihimng** [comment]
make two rows? flex-wrap

**Comment by mitchellchou** [comment]
@ivanng-oursky pls make two rows for RWD. Thanks!
