### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#4]
## Acceptance Criteria
- [x]  Project initialization
- [x]  CICD Setup
- [x]  English strings for now, use i18n to allow extra languages
- [x]  Open source: Allow other chain to build their applications based on our code

## Tasks
- [x] Web: React, Typescript, Tailwind, i18n
- [x] Server: bun, gqlgen, GraphQL, PostgreSQL
- [x] Deployment: Docker Compose, Helm, k8s
- [x] CI: GitHub Actions, Linter, Code Formatter, Vulnerability Audit

**Comment by mitchellchou** [comment]
need 3 env
and stg & prd need access both testnet & mainnet
